# Generated by Django 4.0.4 on 2022-05-02 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worklist', '0003_remove_task_user_profile_task_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='profile',
            new_name='user',
        ),
    ]
