# Generated by Django 4.0.4 on 2022-05-02 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worklist', '0004_rename_profile_task_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='profile',
        ),
    ]
